remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 

title: "Team Baddies Project"
description: "Team Baddies take on their next project."
gitorg: "https://github.com/SRIHITAKOTT1213/FamReunion"
description: "A group of four girls start a project"

